{{- if and .Values.modelCache.tag .Values.modelCache.huggingfaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: model-cache-hf-token
  namespace: {{ .Values.modelCache.namespace | quote }}
  labels:
    app: model-cache
type: Opaque
stringData:
  token: {{ .Values.modelCache.huggingfaceToken | quote }}
{{- end }}
