# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from training.proto.grl.environment.v1 import environment_pb2 as grl_dot_environment_dot_v1_dot_environment__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grl/environment/v1/environment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentServiceStub:
    """EnvironmentService manages Firecracker-backed SWE-bench environments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/CreateEnvironment',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Execute',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Reset',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ResetRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Close',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CloseRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CloseResponse.FromString,
                _registered_method=True)


class EnvironmentServiceServicer:
    """EnvironmentService manages Firecracker-backed SWE-bench environments.
    """

    def CreateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ResetRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CloseRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grl.environment.v1.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grl.environment.v1.EnvironmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService:
    """EnvironmentService manages Firecracker-backed SWE-bench environments.
    """

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/CreateEnvironment',
            grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Execute',
            grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Reset',
            grl_dot_environment_dot_v1_dot_environment__pb2.ResetRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Close',
            grl_dot_environment_dot_v1_dot_environment__pb2.CloseRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
