# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grl/environment/v1/environment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'grl/environment/v1/environment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$grl/environment/v1/environment.proto\x12\x12grl.environment.v1\"+\n\x18\x43reateEnvironmentRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"!\n\x10ListTasksRequest\x12\r\n\x05split\x18\x01 \x01(\t\"0\n\x0eTaskIndexEntry\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05split\x18\x02 \x01(\t\"X\n\x11ListTasksResponse\x12\x31\n\x05tasks\x18\x01 \x03(\x0b\x32\".grl.environment.v1.TaskIndexEntry\x12\x10\n\x08\x65nv_name\x18\x02 \x01(\t\"t\n\x19\x43reateEnvironmentResponse\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\x12\x14\n\x0cmanager_addr\x18\x02 \x01(\t\x12\x1d\n\x15initial_messages_json\x18\x03 \x01(\t\x12\x12\n\ntools_json\x18\x04 \x01(\t\"!\n\x0f\x45valuateRequest\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\"L\n\x10\x45valuateResponse\x12\x0e\n\x06reward\x18\x01 \x01(\x01\x12\x13\n\x0b\x64\x65tail_json\x18\x02 \x01(\t\x12\x13\n\x0binfra_error\x18\x03 \x01(\x08\"K\n\x0e\x45xecuteRequest\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03 \x01(\t\"4\n\x0f\x45xecuteResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08is_error\x18\x02 \x01(\x08\"!\n\x0fTeardownRequest\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\"\x12\n\x10TeardownResponse2\xe2\x03\n\x12\x45nvironmentService\x12X\n\tListTasks\x12$.grl.environment.v1.ListTasksRequest\x1a%.grl.environment.v1.ListTasksResponse\x12p\n\x11\x43reateEnvironment\x12,.grl.environment.v1.CreateEnvironmentRequest\x1a-.grl.environment.v1.CreateEnvironmentResponse\x12R\n\x07\x45xecute\x12\".grl.environment.v1.ExecuteRequest\x1a#.grl.environment.v1.ExecuteResponse\x12U\n\x08\x45valuate\x12#.grl.environment.v1.EvaluateRequest\x1a$.grl.environment.v1.EvaluateResponse\x12U\n\x08Teardown\x12#.grl.environment.v1.TeardownRequest\x1a$.grl.environment.v1.TeardownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grl.environment.v1.environment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEENVIRONMENTREQUEST']._serialized_start=60
  _globals['_CREATEENVIRONMENTREQUEST']._serialized_end=103
  _globals['_LISTTASKSREQUEST']._serialized_start=105
  _globals['_LISTTASKSREQUEST']._serialized_end=138
  _globals['_TASKINDEXENTRY']._serialized_start=140
  _globals['_TASKINDEXENTRY']._serialized_end=188
  _globals['_LISTTASKSRESPONSE']._serialized_start=190
  _globals['_LISTTASKSRESPONSE']._serialized_end=278
  _globals['_CREATEENVIRONMENTRESPONSE']._serialized_start=280
  _globals['_CREATEENVIRONMENTRESPONSE']._serialized_end=396
  _globals['_EVALUATEREQUEST']._serialized_start=398
  _globals['_EVALUATEREQUEST']._serialized_end=431
  _globals['_EVALUATERESPONSE']._serialized_start=433
  _globals['_EVALUATERESPONSE']._serialized_end=509
  _globals['_EXECUTEREQUEST']._serialized_start=511
  _globals['_EXECUTEREQUEST']._serialized_end=586
  _globals['_EXECUTERESPONSE']._serialized_start=588
  _globals['_EXECUTERESPONSE']._serialized_end=640
  _globals['_TEARDOWNREQUEST']._serialized_start=642
  _globals['_TEARDOWNREQUEST']._serialized_end=675
  _globals['_TEARDOWNRESPONSE']._serialized_start=677
  _globals['_TEARDOWNRESPONSE']._serialized_end=695
  _globals['_ENVIRONMENTSERVICE']._serialized_start=698
  _globals['_ENVIRONMENTSERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
