apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grl-observability.clickhouse" . }}-credentials
  labels: {{- include "grl-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.clickhouse.username | quote }}
  password: {{ .Values.clickhouse.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grl-observability.collector" . }}-credentials
  labels: {{- include "grl-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.otelCollector.username | quote }}
  password: {{ .Values.otelCollector.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grl-observability.grafana" . }}-admin
  labels: {{- include "grl-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
