# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grl_proto.grl.environment.v1 import environment_pb2 as grl_dot_environment_dot_v1_dot_environment__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grl/environment/v1/environment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentServiceStub:
    """EnvironmentService manages Firecracker-backed RL environments.

    Per-rollout lifecycle (strict ordering after CreateEnvironment):
    CreateEnvironment → Execute* → Evaluate → Teardown

    Execute accepts bash tools until the agent calls the standard "submit" tool.
    After Evaluate, only Teardown is valid for that env_id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTasks = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/ListTasks',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.CreateEnvironment = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/CreateEnvironment',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Execute',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Evaluate',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.Teardown = channel.unary_unary(
                '/grl.environment.v1.EnvironmentService/Teardown',
                request_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.TeardownRequest.SerializeToString,
                response_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.TeardownResponse.FromString,
                _registered_method=True)


class EnvironmentServiceServicer:
    """EnvironmentService manages Firecracker-backed RL environments.

    Per-rollout lifecycle (strict ordering after CreateEnvironment):
    CreateEnvironment → Execute* → Evaluate → Teardown

    Execute accepts bash tools until the agent calls the standard "submit" tool.
    After Evaluate, only Teardown is valid for that env_id.
    """

    def ListTasks(self, request, context):
        """ListTasks returns the task index loaded at manager startup. Trainers call
        this instead of reading tasks.jsonl from object storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEnvironment(self, request, context):
        """Non-blocking: returns catalog prompt/tools immediately while the VM boots
        asynchronously. Execute/Evaluate return UNAVAILABLE until the env is ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Run one tool call (bash, submit, etc.) inside the environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Grade the finished trajectory. Callable once per env_id. The environment
        owns the reward (e.g. held-out test suite); the manager relays the result.
        Allowed from Ready or Submitted (max turns without submit still grades).
        After Evaluate, only Teardown is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Tear down the environment and free resources. Best-effort; always succeeds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksResponse.SerializeToString,
            ),
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateResponse.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=grl_dot_environment_dot_v1_dot_environment__pb2.TeardownRequest.FromString,
                    response_serializer=grl_dot_environment_dot_v1_dot_environment__pb2.TeardownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grl.environment.v1.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grl.environment.v1.EnvironmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService:
    """EnvironmentService manages Firecracker-backed RL environments.

    Per-rollout lifecycle (strict ordering after CreateEnvironment):
    CreateEnvironment → Execute* → Evaluate → Teardown

    Execute accepts bash tools until the agent calls the standard "submit" tool.
    After Evaluate, only Teardown is valid for that env_id.
    """

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/ListTasks',
            grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/CreateEnvironment',
            grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Execute',
            grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Evaluate',
            grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grl.environment.v1.EnvironmentService/Teardown',
            grl_dot_environment_dot_v1_dot_environment__pb2.TeardownRequest.SerializeToString,
            grl_dot_environment_dot_v1_dot_environment__pb2.TeardownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
